"""
Shared test fixtures for Phoenix-Evo test suite.
"""


import pytest

from core import ImmuneGuard, ImmuneMemory, PhoenixEvo, SkillRegistry


@pytest.fixture
def tmp_root(tmp_path):
    """Provide a temporary root directory for Phoenix-Evo."""
    return tmp_path


@pytest.fixture
def phoenix_evo(tmp_root):
    """Provide a PhoenixEvo instance with temporary root."""
    return PhoenixEvo(base_dir=tmp_root)


@pytest.fixture
def skill_registry(tmp_root):
    """Provide a SkillRegistry instance with temporary root."""
    return SkillRegistry(root=tmp_root)


@pytest.fixture
def immune_guard(tmp_root):
    """Provide an ImmuneGuard instance with temporary root."""
    return ImmuneGuard(root=tmp_root)


@pytest.fixture
def immune_memory(tmp_root):
    """Provide an ImmuneMemory instance with temporary root."""
    return ImmuneMemory(root=tmp_root)


@pytest.fixture
def sample_trajectory():
    """Provide a sample trajectory for testing."""
    return {
        "task_id": "test_traj_001",
        "task_goal": "Fix WSL Chinese path encoding issue",
        "task_type": "coding",
        "risk_level": "low",
        "success": True,
        "started_at": "2026-05-29T10:00:00",
        "completed_at": "2026-05-29T10:05:00",
        "duration": "300.0s",
        "session_id": "test_session",
        "plan": [
            {"step": "Read file", "expected": "Get file content"},
            {"step": "Fix encoding", "expected": "Correct encoding"},
        ],
        "actions": [
            {"action": "read_file", "params": {"path": "/tmp/test.py"}, "result": "OK"},
            {"action": "write_file", "params": {"path": "/tmp/test.py"}, "result": "OK"},
            {"action": "verify_result", "params": {}, "result": "OK"},
        ],
        "tool_calls": [
            {"tool": "terminal", "args": {"command": "ls"}, "raw_result": "file1.txt"},
        ],
        "errors": [],
        "fixes": [],
        "final_output": "File encoding fixed successfully",
        "artifacts": ["/tmp/test.py"],
    }


@pytest.fixture
def sample_skill_candidate():
    """Provide a sample skill candidate for testing."""
    return {
        "skill_id": "skill_test_001",
        "skill_name": "fix_wsl_path_encoding",
        "skill_md": """# Skill: fix_wsl_path_encoding

## Metadata
- **skill_id**: skill_test_001
- **task_type**: coding
- **source_trajectory**: test_traj_001
- **status**: draft

## When to Use
When task goal is: **Fix WSL Chinese path encoding issue** use this skill.

## Inputs
| Name | Required | Example | Source |
| ---- | -------- | ------- | ------ |
| path | [OK] | /tmp/test.py | tool_call_arg |

## Procedure
1. read_file(path=/tmp/test.py)
2. write_file(path=/tmp/test.py, content=fixed)
3. verify_result(path=/tmp/test.py)

## Validation
- verify_result -> OK

## Failure Cases
| Phase | Error | Fix | Success |
| ----- | ----- | --- | ------- |
| - | None | None | [OK] |

## Safety Note
**V0.1 constraint**: This skill is from a single trajectory.

---
*Generated by Phoenix-Evo V0.1*
""",
        "source_trajectory": "test_traj_001",
        "quality_score": 0.85,
    }


@pytest.fixture
def sample_verification_result():
    """Provide a sample verification result for testing."""
    from core.skill_verifier import VerificationResult
    return VerificationResult(
        passed=True,
        confidence=0.9,
        risk_level="low",
        activation_level="draft",
        reason="Verification passed with high confidence",
        warnings=[],
        checked_items={
            "has_trajectory": True,
            "has_goal": True,
            "task_type_safe": True,
            "no_dangerous_content": True,
            "not_overgeneralized": True,
            "not_duplicate": True,
            "has_artifacts": True,
            "has_verification": True,
        },
    )
