"""
Seed Skill Pack — Phoenix-Evo V0.9.0
=====================================
用真实调试经验手写的 5 条种子技能，绕过冷启动困境。
每个 skill 都有可验证的检索价值，接上 SkillRetriever 立即可用。

用法：
    from runtime.seed_skills import SeedSkillLoader
    loader = SeedSkillLoader(phoenix_base_dir="/path/to/Phoenix-Evo")
    result = loader.load_all()   # 写入 skills/active/ 并激活
    print(result)

验收测试：
    from runtime.skill_retriever import SkillRetriever
    retriever = SkillRetriever("/path/to/Phoenix-Evo")
    skills = retriever.retrieve("修复损坏的 Python 文件")
    print(skills[0]["skill_id"])   # 应返回 safe_file_reconstruction
"""

from __future__ import annotations

import json
import logging
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger("seed_skills")

# Phoenix 核心（延迟导入）
_PHOENIX_LOADED = False
try:
    _phoenix_path = str(Path(__file__).parent.parent)
    if _phoenix_path not in sys.path:
        sys.path.insert(0, _phoenix_path)
    from core.skill_registry import SkillRegistry
    _PHOENIX_LOADED = True
except Exception as e:
    logger.warning("Phoenix core not available: %s", e)


# ── SkillCard 模板 ─────────────────────────────────────────────────────────────

def _skill_md(
    skill_id: str,
    skill_name: str,
    task_type: str,
    when_to_use: str,
    procedure: str,
    failure_cases: str,
    safety_note: str,
    quality_score: float = 0.75,
    risk_level: str = "low",
) -> str:
    return f"""# Skill: {skill_name}

## Metadata
- **skill_id**: {skill_id}
- **task_type**: {task_type}
- **source**: seed_pack_v0.9.0
- **seed**: true
- **quality_score**: {quality_score}
- **risk_level**: {risk_level}
- **created_at**: {datetime.now().isoformat()}
- **status**: active

## When to Use
{when_to_use}

## Procedure
{procedure}

## Failure Cases
{failure_cases}

## Safety Note
{safety_note}

---
*Generated by Phoenix-Evo V0.9.0 Seed Pack | 真实调试经验沉淀*
"""


# ── 5 条 Seed Skills ───────────────────────────────────────────────────────────

SEED_SKILLS: list[dict[str, Any]] = [
    {
        "skill_id": "safe_file_reconstruction",
        "skill_name": "Safe File Reconstruction",
        "task_type": "file_repair",
        "when_to_use": (
            "当任务涉及覆写或修复可能损坏的源文件时（尤其是 .py .vue .html 等文本文件），"
            "先写 /tmp/ 临时文件验证合法性，再迁移到目标路径。\n"
            "典型场景：patch 工具在 WSL 中文路径下写入 null 字节导致文件损坏；"
            "覆盖配置文件前没有备份；写入大文件时进程中断产生截断。"
        ),
        "procedure": """1. **读源文件前先备份**：cp original.py /tmp/original_backup.py
2. **写入前先写临时文件**：写到 /tmp/verified.py，用 ast.parse() 或 py_compile 验证语法
3. **验证后再迁移**：diff /tmp/verified.py 原始内容，确认无误后 mv /tmp/verified.py 目标路径
4. **如果文件不存在**：先 touch /tmp/empty_placeholder.py 再逐步写入关键内容
5. **ChromdDB/向量库文件**尤其注意：不要直接覆写 .sqlite .sqlite-journal 等数据库文件，先验证""",
        "failure_cases": """| 错误阶段 | 错误信息 | 修复策略 |
| -------- | -------- | -------- |
| 写入损坏 | patch 写入 null 字节 | 立即用 /tmp 备份恢复：cp /tmp/original_backup.py 目标路径 |
| 语法未验证 | SyntaxError: unexpected EOF | py_compile 验证通过后再迁移 |
| 进程中断 | FileNotFoundError | 先检查文件是否存在，再决定是恢复还是重建 |
| 中文路径写入失败 | UnicodeEncodeError | 改用 /tmp 中转，写入前 os.fspath() 确保路径编码正确 |""",
        "safety_note": (
            "[medium_risk] 直接覆写生产文件是危险操作，每次覆写前必须验证语法。"
            "本技能来自 WSL 中文路径 patch 工具 null 字节损坏事件的真实调试经验。"
        ),
        "quality_score": 0.82,
        "risk_level": "medium",
    },
    {
        "skill_id": "signature_first_debugging",
        "skill_name": "Signature First Debugging",
        "task_type": "debug",
        "when_to_use": (
            "当遇到 TypeError: xxx() takes N positional arguments but M were given、"
            "AttributeError: 'xxx' object has no attribute 'yyy'、"
            "ImportError: cannot import name 'xxx' from 'yyy' 等接口级别错误时，"
            "在调用接口前先读函数签名或类定义，从签名本身反推正确用法。"
        ),
        "procedure": """1. **遇到接口错误立即查签名**：不要反复猜测参数，用 inspect.signature() 或 read_file 读源码
2. **Python 对象**：execute_code(code=import inspect; print(inspect.signature(func_or_class)))
3. **外部工具/API**：用 tool_schema 中的 parameters 定义对照自己传的参数名
4. **匹配签名后再调用**：发现参数数量/名称不匹配时，用 named args 而非位置 args 提高可读性
5. **如果签名本身有问题**（参数名拼写错误、类型注解错误），记录下来作为潜在的代码 bug 反馈""",
        "failure_cases": """| 错误阶段 | 错误信息 | 修复策略 |
| -------- | -------- | -------- |
| TypeError 参数数量不匹配 | takes N positional arguments but M were given | 用 named kwargs 而非位置传参，对照 signature() 逐一核对 |
| AttributeError 属性不存在 | 'xxx' object has no attribute 'yyy' | 先 hasattr(obj, 'yyy') 检查，再读源码确认是否存在别名或拼写差异 |
| ImportError 导入失败 | cannot import name 'xxx' from 'yyy' | 用 help(yyy) 或 __all__ 查可用名称，确认大小写或版本差异 |
| 函数签名与文档不符 | 文档说支持某参数但报 TypeError | 以运行时 signature() 为准，文档可能过时 |""",
        "safety_note": (
            "[low_risk] 纯诊断方法，不涉及写入操作。"
            "signature-first 策略可以把接口错误调试时间从 10+ 分钟缩短到 1 分钟以内。"
        ),
        "quality_score": 0.85,
        "risk_level": "low",
    },
    {
        "skill_id": "syntax_validation_before_overwrite",
        "skill_name": "Syntax Validation Before Overwrite",
        "task_type": "file_repair",
        "when_to_use": (
            "在覆写任何 Python/Vue/HTML/JS 文本文件之前，用 ast.parse() 或 py_compile "
            "先验证语法合法性，发现 SyntaxError 立即停止覆写操作，防止把文件修成损坏状态。"
        ),
        "procedure": """1. **覆写前先 parse 验证**：
   execute_code(code="import ast; ast.parse(open('目标文件路径').read())")
2. **如果 parse 失败**（文件已损坏）：先从备份恢复，或用 /tmp/ 版本重新写
3. **写临时文件时同步验证**：写到 /tmp/ 时就做一次 py_compile，确认无错后再迁移
4. **批量覆写前抽检**：多个文件覆写前先抽 1-2 个验证语法，防止连带损坏
5. **覆写后二次验证**：完成迁移后再读一次，确认文件内容完整（非截断、无 null 字节）""",
        "failure_cases": """| 错误阶段 | 错误信息 | 修复策略 |
| -------- | -------- | -------- |
| 源文件本身已损坏 | SyntaxError: unexpected EOF in multi-line statement | 先恢复备份，再重新写入合法内容，不要直接覆写损坏文件 |
| 写入过程被截断 | 写入后文件长度异常 | 读取文件内容，确认长度符合预期，如有异常从备份恢复 |
| 编码错误导致 parse 失败 | UnicodeDecodeError | 用 encoding='utf-8' 或 'gbk' 显式指定编码重读，确认文件编码 |
| py_compile 静默通过但运行报错 | ImportError 运行时才出现 | parse 验证语法，import 验证模块级别依赖，分两步检查 |""",
        "safety_note": (
            "[high_risk] 覆写文件前必须验证语法已成硬性规则。 "
            "本技能来自多次文件损坏后需要从备份恢复的真实教训。"
        ),
        "quality_score": 0.80,
        "risk_level": "high",
    },
    {
        "skill_id": "error_message_as_contract_signal",
        "skill_name": "Error Message as Contract Signal",
        "task_type": "debug",
        "when_to_use": (
            "当任务遇到 Python 报错信息（Traceback）时，把错误类型当作接口契约的违反信号：\n"
            "- TypeError → 签名/参数契约违反\n"
            "- SyntaxError → 文件内容损坏或格式错误\n"
            "- ImportError → 模块路径/版本/名称契约违反\n"
            "- AttributeError → 对象结构契约违反\n"
            "通过错误类型推断错误根源，比猜原因快 5-10 倍。"
        ),
        "procedure": """1. **提取错误类型作为第一信号**：TypeError → 查签名；SyntaxError → 验证文件完整性；ImportError → 查路径
2. **按错误类型走对应路径**：
   - TypeError: inspect.signature() → 确认参数名和数量 → 修正调用
   - SyntaxError: 读文件前 10 行 → 检查缩进/括号/字符串配对 → 定位损坏位置
   - ImportError: help(module) / __all__ 查可用名称 → 确认版本和导入路径
   - AttributeError: hasattr() 检查属性 → 读源码确认属性名或使用 getattr(obj, name, default)
3. **记录错误类型作为技能挖掘素材**：把「错误类型 → 根因 → 修复路径」存入 Phoenix trajectory
4. **高频 ImportError 处理**：优先用 try/import 捕获，确认是路径问题还是名称问题再决定是修代码还是装包
5. **AttributeError 特殊处理**：检查属性是否存在 hasattr()，如果存在但仍报错，可能是继承层次或 mixin 问题""",
        "failure_cases": """| 错误阶段 | 错误信息 | 修复策略 |
| -------- | -------- | -------- |
| TypeError 反复出现 | 每次调用都报不同参数错误 | 用 signature() 完整读取函数签名，用 kwargs 传参避免位置错误 |
| SyntaxError 静默产生 | 写入后发现文件内容有空字节 | 用二进制读入检查 b'\\x00' 出现位置，确认后从备份恢复 |
| ImportError 偶发 | 某些机器上 ImportError 某些不报错 | 统一使用绝对导入 from package import name 而非相对导入 |
| AttributeError 在 hasattr 为 True 时仍报错 | 属性存在但访问时报 Error | 检查描述符协议（property/descriptor），用 getattr 而非直接访问 |""",
        "safety_note": (
            "[low_risk] 纯诊断方法，不涉及写入操作。"
            "错误类型是最被低估的调试资源，高手把错误当合同违反信号看，而非随机故障。"
        ),
        "quality_score": 0.78,
        "risk_level": "low",
    },
    {
        "skill_id": "demo_repair_workflow",
        "skill_name": "Demo Repair Workflow",
        "task_type": "debug",
        "when_to_use": (
            "当任务涉及修复 demo、修复测试失败（test 跑不过）、修复演示脚本时，"
            "用最小复现→单点修复→全量验证三步走，而不是直接大改代码。"
        ),
        "procedure": """1. **最小复现**：找到 fail 的测试/命令，用最小参数、最少依赖复现问题
   - 失败命令：demo.py --arg1=x --arg2=y → 先用 demo.py 单参数跑
   - 测试失败：pytest tests/test_xxx.py::test_name -v → 先去掉 -v 和其他 flag 只看最小失败
2. **单点修复**：找到失败点后，只改那一个最小单元，不要同时改多个地方
   - 如果是函数签名问题：只修那一个函数
   - 如果是导入问题：只修那一个 import
   - 如果是数据问题：只修那一条数据
3. **全量验证**：修复后立即跑 demo/test，确认修复没有引入新问题
   - pytest 而不是 unittest（更详细的 traceback）
   - demo.py --help 或 demo.py --dry-run 先做烟雾测试
4. **回退准备**：修复前备份 git commit 或 /tmp/ 备份，修复出问题能一键回退
5. **回归测试**：用 git diff 或手动对比，确认修复的代码行数和影响的函数数量都是最小的""",
        "failure_cases": """| 错误阶段 | 错误信息 | 修复策略 |
| -------- | -------- | -------- |
| 最小复现找不到根因 | 单参数跑通过但组合参数失败 | 逐步加参数，用二分法隔离，先加风险最高的参数 |
| 单点修复后 demo 通过但测试失败 | demo 和 test 的断言条件不一致 | 检查 test 和 demo 是否在验证同一行为，可能是测试用例本身写错了 |
| 修复引入新问题 | 修复了 A 功能的 bug 导致 B 功能损坏 | 立即回退到备份，用 git stash 或 /tmp 备份恢复 |
| 多次修复仍失败 | 修复→测试→再修复循环超过 3 次 | 停下来分析根因，可能是架构问题而非单点 bug，重新评估修复策略 |""",
        "safety_note": (
            "[medium_risk] 修复 demo 时注意备份，引入新问题的概率不低。"
            "本技能来自多次修复改多不如改少、用最小改动换最大收益的真实经验。"
        ),
        "quality_score": 0.83,
        "risk_level": "medium",
    },
]


# ── SeedSkillLoader ─────────────────────────────────────────────────────────────

class SeedSkillLoader:
    """
    初始化 Phoenix 技能库：写入 5 条 seed skills 并激活。
    只写 skill .md 文件，不改 Phoenix 核心代码。
    """

    def __init__(self, phoenix_base_dir: Path | str | None = None):
        self.base_dir = Path(phoenix_base_dir or Path(__file__).parent.parent)
        self.registry = SkillRegistry(root=self.base_dir) if _PHOENIX_LOADED else None

    def load_all(self) -> dict[str, Any]:
        """写入并激活所有 5 条 seed skills。幂等：已激活的跳过。"""
        if not _PHOENIX_LOADED or self.registry is None:
            return {
                "status": "skipped",
                "reason": f"Phoenix not loaded (err={None})",
                "loaded": [],
                "activated": [],
                "skipped": [],
            }

        loaded: list[str] = []
        activated: list[str] = []
        skipped: list[str] = []

        for skill in SEED_SKILLS:
            skill_id = skill["skill_id"]
            active_path = self.base_dir / "skills" / "active" / f"{skill_id}.md"

            # 如果已经存在 active 版本，跳过
            if active_path.exists():
                logger.info("Skip %s (already exists)", skill_id)
                skipped.append(skill_id)
                continue

            # 写入 active 目录
            skill_md = _skill_md(
                skill_id=skill["skill_id"],
                skill_name=skill["skill_name"],
                task_type=skill["task_type"],
                when_to_use=skill["when_to_use"],
                procedure=skill["procedure"],
                failure_cases=skill["failure_cases"],
                safety_note=skill["safety_note"],
                quality_score=skill["quality_score"],
                risk_level=skill["risk_level"],
            )

            active_path.parent.mkdir(parents=True, exist_ok=True)
            active_path.write_text(skill_md, encoding="utf-8")
            logger.info("Written %s", active_path)

            # 注册到 index
            index = self.registry._load_index()
            index[skill_id] = {
                "skill_id": skill_id,
                "skill_name": skill["skill_name"],
                "status": "active",
                "source": "seed_pack_v0.9.0",
                "seed": True,
                "quality_score": skill["quality_score"],
                "risk_level": skill["risk_level"],
                "task_type": skill["task_type"],
                "created_at": datetime.now().isoformat(),
                "activated_at": datetime.now().isoformat(),
                "approved_by": "seed_pack",
                "usage_count": 0,
                "success_count": 0,
                "success_rate": None,
                "last_used": None,
            }
            self.registry._save_index(index)

            loaded.append(skill_id)
            activated.append(skill_id)

        return {
            "status": "ok",
            "loaded": loaded,
            "activated": activated,
            "skipped": skipped,
            "total_active": len(self.registry.get_active_skills()),
        }

    def verify(self) -> dict[str, Any]:
        """验证 retrieve 能针对典型任务检索到相关 skills。"""
        if not _PHOENIX_LOADED:
            return {"status": "skipped", "reason": "Phoenix not loaded"}

        from runtime.skill_retriever import SkillRetriever
        retriever = SkillRetriever(base_dir=self.base_dir)

        test_queries = [
            ("修复损坏的 Python 文件", "safe_file_reconstruction"),
            ("SyntaxError 文件损坏", "syntax_validation_before_overwrite"),
            ("demo 测试失败怎么修", "demo_repair_workflow"),
            ("TypeError 参数数量不对", "signature_first_debugging"),
            ("看到错误信息不知道原因", "error_message_as_contract_signal"),
        ]

        results = {}
        for query, expected_skill_id in test_queries:
            skills = retriever.retrieve(query, top_k=3)
            matched_ids = [s["skill_id"] for s in skills]
            hit = expected_skill_id in matched_ids
            results[query] = {
                "expected": expected_skill_id,
                "retrieved": matched_ids,
                "hit": hit,
            }

        all_hit = all(r["hit"] for r in results.values())
        return {
            "status": "pass" if all_hit else "fail",
            "queries": results,
            "total_active": len(self.registry.get_active_skills()),
        }


# ── CLI ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    parser = argparse.ArgumentParser(description="Phoenix-Evo V0.9.0 Seed Skill Pack")
    parser.add_argument("--phoenix-dir", type=str, default=None, help="Phoenix-Evo 根目录")
    parser.add_argument("--verify", action="store_true", help="加载后运行 retrieve 验证测试")
    args = parser.parse_args()

    base_dir = Path(args.phoenix_dir) if args.phoenix_dir else Path(__file__).parent.parent

    print("\n=== Phoenix-Evo V0.9.0 Seed Skill Pack ===")
    print(f"Base dir: {base_dir}\n")

    loader = SeedSkillLoader(phoenix_base_dir=base_dir)
    result = loader.load_all()
    print(f"Load result: {json.dumps(result, ensure_ascii=False, indent=2)}\n")

    if args.verify:
        print("=== Verify retrieve ===\n")
        v = loader.verify()
        print(json.dumps(v, ensure_ascii=False, indent=2))
        if v["status"] == "pass":
            print("\n✓ All retrieve tests passed")
        else:
            print("\n✗ Some retrieve tests failed")
